# Mod metadata
# The version of your addon
addonVersion=1.1
# The version your addon needs to work
targetMWEVersion=4.7
# The name of your addon, this will be used as the name of the .jar
addonName=Sleep Addon
# The id of your addon this should never change
addonId=exampleaddon
# Make this match with the package name that you choose
modPackageName=me.standonts
